name: Lint Files
'on':
  push:
    branches:
      - '*'
      - '!master'
jobs:
  lint-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm run lint
